import { useEffect } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { markNotificationsRead } from "@/api";
import { useNotifications } from "@/data";
import { useSession } from "@/session";
import { theme } from "@/theme";

export default function NotificationsScreen(){const router=useRouter();const insets=useSafeAreaInsets();const {token}=useSession();const notices=useNotifications();useEffect(()=>{if(token&&notices.data?.unread)void markNotificationsRead(token)},[token,notices.data?.unread]);return <View style={[s.page,{paddingTop:insets.top+10}]}><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.close}>Close</Text></Pressable><Text style={s.topTitle}>Notifications</Text><View style={{width:42}}/></View><ScrollView contentContainerStyle={[s.content,{paddingBottom:insets.bottom+30}]}>{notices.loading&&!notices.data?<ActivityIndicator color={theme.accent} style={{marginTop:40}}/>:null}{notices.data?.notifications.length?notices.data.notifications.map(item=><View key={item.id} style={s.item}><View style={[s.icon,!item.read&&s.iconOn]}><Text style={s.iconText}>{item.kind==="band"?"V1":item.kind==="social"?"@":"↗"}</Text></View><View style={{flex:1}}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.itemBody}>{item.body}</Text><Text style={s.time}>{new Date(item.createdAt).toLocaleDateString()}</Text></View>{!item.read?<View style={s.unread}/>:null}</View>):<View style={s.empty}><Text style={s.emptyTitle}>You’re all caught up.</Text><Text style={s.emptyBody}>New follows, Map check-ins and V1 alerts will appear here.</Text></View>}</ScrollView></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg},top:{height:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:theme.line},close:{color:theme.accent,fontSize:12,fontWeight:"800"},topTitle:{color:theme.ink,fontSize:11,fontWeight:"900",letterSpacing:1.5,textTransform:"uppercase"},content:{paddingHorizontal:18,paddingTop:8},item:{flexDirection:"row",gap:13,paddingVertical:16,borderBottomWidth:1,borderBottomColor:theme.line},icon:{width:44,height:44,borderRadius:15,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.line,alignItems:"center",justifyContent:"center"},iconOn:{borderColor:theme.accent,backgroundColor:theme.accentSoft},iconText:{color:theme.accent,fontSize:11,fontWeight:"900"},itemTitle:{color:theme.ink,fontSize:13,fontWeight:"800"},itemBody:{color:theme.ink2,fontSize:11,lineHeight:17,marginTop:4},time:{color:theme.muted,fontSize:10,marginTop:6},unread:{width:6,height:6,borderRadius:3,backgroundColor:theme.accent,marginTop:8},empty:{alignItems:"center",padding:36,borderRadius:24,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface},emptyTitle:{color:theme.ink,fontSize:16,fontWeight:"800"},emptyBody:{color:theme.ink2,fontSize:12,lineHeight:18,textAlign:"center",marginTop:7}});
