import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAppState } from "@/app-state";
import { usePreferences, locales, localeMeta, type AppLocale } from "@/preferences";
import { setAppearance } from "@/appearance";
import { useSession } from "@/session";
import { appearanceMode, display, theme, type AppearanceMode } from "@/theme";

export default function SettingsScreen() {
  const router=useRouter();const insets=useSafeAreaInsets();const {profile,saveProfile}=useAppState();const {signOut}=useSession();const preferences=usePreferences();const sharing=profile?.profile?.shareWithCreators??false;
  return <ScrollView style={s.page} contentContainerStyle={[s.content,{paddingTop:insets.top+10,paddingBottom:insets.bottom+34}]}>
    <View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.brand}>TERRIFIT</Text><View style={{width:50}}/></View>
    <Text style={s.eyebrow}>Your app</Text><Text style={s.title}>{preferences.t("settings").toUpperCase()}.</Text>
    <Text style={s.section}>{preferences.t("appearance")}</Text><View style={s.segment}>{(["dark","light","system"] as AppearanceMode[]).map(mode=><Pressable key={mode} onPress={()=>void setAppearance(mode)} style={[s.segmentItem,appearanceMode===mode&&s.segmentOn]}><Text style={s.modeIcon}>{mode==="dark"?"◐":mode==="light"?"☀":"◉"}</Text><Text style={[s.segmentText,appearanceMode===mode&&s.segmentTextOn]}>{preferences.t(mode)}</Text></Pressable>)}</View>
    <Text style={s.hint}>System follows your device. Switching reloads the app so every screen picks up the new palette.</Text>
    <Text style={s.section}>{preferences.t("language")}</Text><View style={s.languages}>{locales.map(item=><Language key={item} locale={item} active={preferences.locale===item} onPress={()=>void preferences.setLocale(item)}/>)}</View>
    <Text style={s.hint}>Navigation and new product surfaces use your chosen language. Arabic enables right-to-left support.</Text>
    <Text style={s.section}>Privacy</Text><View style={s.card}><Setting title="Share trends with my coach" detail="Your private check-ins stay private. This shares high-level progress trends only." value={sharing} onValueChange={value=>void saveProfile({shareWithCreators:value})}/><Setting title="Discoverable profile" detail="Let athletes find your public posts and profile." value /></View>
    <Text style={s.section}>Account</Text><View style={s.card}><Info title="Signed in as" detail={profile?.user.email??"Terrifit member"}/><Pressable onPress={()=>router.push("/edit-profile" as never)} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>Profile details</Text><Text style={s.rowDetail}>Name, handle, bio and training goal</Text></View><Text style={s.arrow}>›</Text></Pressable></View>
    <Pressable onPress={()=>void signOut()} style={s.signout}><Text style={s.signoutText}>Sign out on this device</Text></Pressable>
  </ScrollView>;
}
function Language({locale,active,onPress}:{locale:AppLocale;active:boolean;onPress:()=>void}){const item=localeMeta[locale];return <Pressable onPress={onPress} style={[s.language,active&&s.languageOn]}><View style={{flex:1}}><Text style={[s.languageNative,active&&s.languageNativeOn]}>{item.label}</Text><Text style={s.languageEnglish}>{item.english}</Text></View>{active?<View style={s.check}><Text style={s.checkText}>✓</Text></View>:null}</Pressable>}
function Setting({title,detail,value,onValueChange}:{title:string;detail:string;value:boolean;onValueChange?:(value:boolean)=>void}){return <View style={s.row}><View style={{flex:1,paddingRight:12}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{false:theme.lineStrong,true:theme.accentSoft}} thumbColor={value?theme.accent:theme.muted}/></View>}
function Info({title,detail}:{title:string;detail:string}){return <View style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg},content:{paddingHorizontal:20},top:{height:46,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{color:theme.ink2,fontSize:13,fontWeight:"700",width:50},brand:{color:theme.ink,fontSize:10,fontWeight:"900",letterSpacing:2},eyebrow:{color:theme.accent,fontSize:10,fontWeight:"900",letterSpacing:2,textTransform:"uppercase",marginTop:25},title:{color:theme.ink,fontFamily:display,fontSize:44,marginTop:7},section:{color:theme.accent,fontSize:10,fontWeight:"900",letterSpacing:1.5,textTransform:"uppercase",marginTop:26,marginBottom:10},segment:{flexDirection:"row",gap:8},segmentItem:{flex:1,height:72,borderRadius:19,borderWidth:1,borderColor:theme.lineStrong,backgroundColor:theme.surface,alignItems:"center",justifyContent:"center",gap:6},segmentOn:{borderColor:theme.accent,backgroundColor:theme.accentSoft},modeIcon:{color:theme.ink,fontSize:19},segmentText:{color:theme.muted,fontSize:10,fontWeight:"900",textTransform:"uppercase",letterSpacing:.8},segmentTextOn:{color:theme.ink},hint:{color:theme.muted,fontSize:10,lineHeight:14,marginTop:9},languages:{flexDirection:"row",flexWrap:"wrap",gap:8},language:{width:"48.5%",minHeight:61,borderRadius:17,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface,flexDirection:"row",alignItems:"center",paddingHorizontal:13},languageOn:{borderColor:theme.accent,backgroundColor:theme.accentSoft},languageNative:{color:theme.ink,fontSize:12,fontWeight:"800"},languageNativeOn:{color:theme.accent},languageEnglish:{color:theme.muted,fontSize:10,marginTop:3},check:{width:20,height:20,borderRadius:10,backgroundColor:theme.accent,alignItems:"center",justifyContent:"center"},checkText:{color:"#fff",fontSize:10,fontWeight:"900"},card:{borderRadius:21,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface,overflow:"hidden"},row:{minHeight:76,flexDirection:"row",alignItems:"center",paddingHorizontal:16,paddingVertical:13,borderBottomWidth:1,borderBottomColor:theme.line},rowTitle:{color:theme.ink,fontSize:13,fontWeight:"800"},rowDetail:{color:theme.muted,fontSize:10,lineHeight:15,marginTop:4},arrow:{color:theme.muted,fontSize:24},signout:{height:50,borderRadius:25,borderWidth:1,borderColor:theme.lineStrong,alignItems:"center",justifyContent:"center",marginTop:28},signoutText:{color:theme.poor,fontSize:10,fontWeight:"900",letterSpacing:1,textTransform:"uppercase"}});
