import type { Locale } from "./config";

export type MarketingUi = {
  nav: [string, string, string, string, string];
  signIn: string;
  chooseLanguage: string;
  countryQuestion: string;
  countryPlaceholder: string;
  partner: string;
  organization: string;
  comingSoon: string;
};

export const marketingUi: Record<Locale, MarketingUi> = {
  en:{nav:["App","Band","Maps","Creators","Shop"],signIn:"Sign in",chooseLanguage:"Choose language",countryQuestion:"Where are you from?",countryPlaceholder:"Your country",partner:"Partner",organization:"Organisation",comingSoon:"Coming soon"},
  es:{nav:["App","Pulsera","Planes","Creadores","Tienda"],signIn:"Iniciar sesión",chooseLanguage:"Elegir idioma",countryQuestion:"¿De dónde eres?",countryPlaceholder:"Tu país",partner:"Socio",organization:"Organización",comingSoon:"Próximamente"},
  ar:{nav:["التطبيق","السوار","الخطط","المبدعون","المتجر"],signIn:"تسجيل الدخول",chooseLanguage:"اختر اللغة",countryQuestion:"من أين أنت؟",countryPlaceholder:"بلدك",partner:"شريك",organization:"المؤسسة",comingSoon:"قريبًا"},
  fr:{nav:["App","Bracelet","Programmes","Créateurs","Boutique"],signIn:"Se connecter",chooseLanguage:"Choisir la langue",countryQuestion:"D’où venez-vous ?",countryPlaceholder:"Votre pays",partner:"Partenaire",organization:"Organisation",comingSoon:"Bientôt"},
  de:{nav:["App","Band","Pläne","Creator","Shop"],signIn:"Anmelden",chooseLanguage:"Sprache wählen",countryQuestion:"Woher kommst du?",countryPlaceholder:"Dein Land",partner:"Partner",organization:"Organisation",comingSoon:"Demnächst"},
  nl:{nav:["App","Band","Programma’s","Makers","Winkel"],signIn:"Inloggen",chooseLanguage:"Taal kiezen",countryQuestion:"Waar kom je vandaan?",countryPlaceholder:"Jouw land",partner:"Partner",organization:"Organisatie",comingSoon:"Binnenkort"},
  pt:{nav:["App","Pulseira","Planos","Criadores","Loja"],signIn:"Entrar",chooseLanguage:"Escolher idioma",countryQuestion:"De onde és?",countryPlaceholder:"O teu país",partner:"Parceiro",organization:"Organização",comingSoon:"Em breve"},
  it:{nav:["App","Bracciale","Programmi","Creator","Negozio"],signIn:"Accedi",chooseLanguage:"Scegli la lingua",countryQuestion:"Di dove sei?",countryPlaceholder:"Il tuo paese",partner:"Partner",organization:"Organizzazione",comingSoon:"Prossimamente"},
  tr:{nav:["Uygulama","Bileklik","Programlar","Üreticiler","Mağaza"],signIn:"Giriş yap",chooseLanguage:"Dil seç",countryQuestion:"Nerelisin?",countryPlaceholder:"Ülken",partner:"İş ortağı",organization:"Kuruluş",comingSoon:"Yakında"},
  ru:{nav:["Приложение","Браслет","Планы","Авторы","Магазин"],signIn:"Войти",chooseLanguage:"Выбрать язык",countryQuestion:"Откуда вы?",countryPlaceholder:"Ваша страна",partner:"Партнёр",organization:"Организация",comingSoon:"Скоро"},
};

export type MarketingDetails = {
  band: [string,string,string,[string,string,string,string],string];
  app: [string,string,string,string,string,string];
  lifestyle: [string,string,string,string];
  shop: [string,string,string,string,string,string,string,string];
  waitlist: [string,string,string,string,string];
  common: [string,string,string,string,string,string,string,string,string,string];
  signin: [string,string,string,string,string,string];
};

export const marketingDetails: Record<Locale, MarketingDetails> = {
  en:{band:["The Terrifit Band","One band. Every version of you.","Continuous performance sensing for training, work and everything after.",["Continuous sensing","Side-glance time","4-dot battery","Woven for real life"],"Explore the band"],app:["One platform","Dark + light interfaces","Download on the","Get it on","On the list","founding members so far"],lifestyle:["Train.","Work.","Live.","Get terrificly fit."],shop:["Creator marketplace","Fuel your best.","Terrifit originals and products from verified partners.","Affiliate","We may earn a commission.","View the marketplace","Verified partner","Terrifit original"],waitlist:["Pioneers receive a special launch gift.","founding members","creator places left","Place secured.","Done"],common:["Recovery","Strain","Sleep","Map progress","Ready","Moderate","Optimal","Week","weeks","Explore"],signin:["Member access","Welcome back.","Access is opening in waves to founding members.","Email","Password","Not a member? Join the waitlist"]},
  es:{band:["La pulsera Terrifit","Una pulsera. Todas tus versiones.","Medición continua del rendimiento para entrenar, trabajar y todo lo demás.",["Medición continua","Hora de un vistazo","Batería de 4 puntos","Tejida para la vida real"],"Explorar la pulsera"],app:["Una plataforma","Interfaces oscura y clara","Descargar en","Disponible en","En la lista","miembros fundadores hasta ahora"],lifestyle:["Entrena.","Trabaja.","Vive.","Una señal. Todas tus versiones."],shop:["Marketplace de creadores","Alimenta tu mejor versión.","Productos Terrifit y de socios verificados.","Afiliación","Podemos recibir una comisión.","Ver el marketplace","Socio verificado","Original Terrifit"],waitlist:["Los pioneros recibirán un regalo especial de lanzamiento.","miembros fundadores","plazas de creador disponibles","Plaza asegurada.","Listo"],common:["Recuperación","Esfuerzo","Sueño","Progreso del plan","Listo","Moderado","Óptimo","Semana","semanas","Explorar"],signin:["Acceso de miembros","Bienvenido de nuevo.","El acceso se abre por fases para los miembros fundadores.","Correo","Contraseña","¿Aún no eres miembro? Únete a la lista"]},
  ar:{band:["سوار تيريفت","سوار واحد. لكل نسخة منك.","قياس مستمر للأداء في التدريب والعمل وكل ما بعدهما.",["استشعار مستمر","الوقت بنظرة جانبية","بطارية بأربع نقاط","نسيج للحياة اليومية"],"استكشف السوار"],app:["منصة واحدة","واجهتان داكنة وفاتحة","حمّل من","متوفر على","في القائمة","أعضاء مؤسسون حتى الآن"],lifestyle:["تدرّب.","اعمل.","عِش.","إشارة واحدة. لكل نسخة منك."],shop:["سوق المبدعين","غذِّ أفضل أداء لديك.","منتجات تيريفت ومنتجات شركاء موثوقين.","تسويق بالعمولة","قد نحصل على عمولة.","استكشف السوق","شريك موثّق","منتج تيريفت أصلي"],waitlist:["يحصل الروّاد على هدية إطلاق خاصة.","أعضاء مؤسسون","أماكن متبقية للمبدعين","تم حجز مكانك.","تم"],common:["التعافي","الإجهاد","النوم","تقدم الخطة","جاهز","متوسط","مثالي","الأسبوع","أسابيع","استكشف"],signin:["دخول الأعضاء","مرحبًا بعودتك.","يُفتح الوصول تدريجيًا للأعضاء المؤسسين.","البريد الإلكتروني","كلمة المرور","لست عضوًا؟ انضم إلى قائمة الانتظار"]},
  fr:{band:["Le bracelet Terrifit","Un bracelet. Toutes vos versions.","Mesure continue des performances à l’entraînement, au travail et au-delà.",["Mesure continue","Heure en un coup d’œil","Batterie à 4 points","Tissé pour la vraie vie"],"Découvrir le bracelet"],app:["Une plateforme","Interfaces sombre et claire","Télécharger dans","Disponible sur","Sur la liste","membres fondateurs à ce jour"],lifestyle:["Entraînez-vous.","Travaillez.","Vivez.","Un signal. Toutes vos versions."],shop:["Marketplace des créateurs","Nourrissez votre meilleur niveau.","Produits Terrifit et partenaires vérifiés.","Affiliation","Nous pouvons percevoir une commission.","Voir le marketplace","Partenaire vérifié","Original Terrifit"],waitlist:["Les pionniers recevront un cadeau de lancement spécial.","membres fondateurs","places créateur restantes","Place réservée.","Terminé"],common:["Récupération","Effort","Sommeil","Progression du programme","Prêt","Modéré","Optimal","Semaine","semaines","Découvrir"],signin:["Accès membre","Bon retour.","L’accès s’ouvre progressivement aux membres fondateurs.","E-mail","Mot de passe","Pas encore membre ? Rejoignez la liste"]},
  de:{band:["Das Terrifit Band","Ein Band. Jede Version von dir.","Kontinuierliche Leistungsmessung für Training, Arbeit und alles danach.",["Kontinuierliche Messung","Uhrzeit auf einen Blick","4-Punkt-Akku","Für den Alltag gewebt"],"Band entdecken"],app:["Eine Plattform","Dunkle und helle Oberfläche","Laden im","Jetzt bei","Auf der Liste","Gründungsmitglieder bisher"],lifestyle:["Trainiere.","Arbeite.","Lebe.","Ein Signal. Jede Version von dir."],shop:["Creator-Marktplatz","Hol das Beste aus dir.","Terrifit-Produkte und Angebote geprüfter Partner.","Affiliate","Wir können eine Provision erhalten.","Marktplatz ansehen","Geprüfter Partner","Terrifit Original"],waitlist:["Pioniere erhalten ein besonderes Launch-Geschenk.","Gründungsmitglieder","freie Creator-Plätze","Platz gesichert.","Fertig"],common:["Erholung","Belastung","Schlaf","Map-Fortschritt","Bereit","Moderat","Optimal","Woche","Wochen","Entdecken"],signin:["Mitgliederzugang","Willkommen zurück.","Der Zugang wird schrittweise für Gründungsmitglieder geöffnet.","E-Mail","Passwort","Noch kein Mitglied? Zur Warteliste"]},
  nl:{band:["De Terrifit Band","Eén band. Elke versie van jou.","Continue prestatiemeting voor training, werk en alles daarna.",["Continue meting","Tijd in één oogopslag","Batterij met 4 punten","Geweven voor het echte leven"],"Ontdek de band"],app:["Eén platform","Donkere en lichte interface","Download in de","Beschikbaar op","Op de lijst","oprichters tot nu toe"],lifestyle:["Train.","Werk.","Leef.","Eén signaal. Elke versie van jou."],shop:["Marketplace voor makers","Voed je beste zelf.","Terrifit-producten en producten van geverifieerde partners.","Affiliate","We kunnen commissie ontvangen.","Bekijk de marketplace","Geverifieerde partner","Terrifit origineel"],waitlist:["Pioniers ontvangen een speciaal lanceringscadeau.","oprichters","makerplekken over","Plek bevestigd.","Klaar"],common:["Herstel","Belasting","Slaap","Voortgang","Klaar","Gematigd","Optimaal","Week","weken","Ontdek"],signin:["Ledentoegang","Welkom terug.","Toegang opent gefaseerd voor oprichters.","E-mail","Wachtwoord","Nog geen lid? Meld je aan"]},
  pt:{band:["A pulseira Terrifit","Uma pulseira. Todas as tuas versões.","Medição contínua para treino, trabalho e tudo o que vem depois.",["Medição contínua","Hora num relance","Bateria de 4 pontos","Tecido para a vida real"],"Explorar a pulseira"],app:["Uma plataforma","Interfaces escura e clara","Descarregar na","Disponível no","Na lista","membros fundadores até agora"],lifestyle:["Treina.","Trabalha.","Vive.","Um sinal. Todas as tuas versões."],shop:["Marketplace de criadores","Alimenta o teu melhor.","Produtos Terrifit e de parceiros verificados.","Afiliado","Podemos receber uma comissão.","Ver o marketplace","Parceiro verificado","Original Terrifit"],waitlist:["Os pioneiros receberão um presente especial de lançamento.","membros fundadores","lugares de criador disponíveis","Lugar garantido.","Concluído"],common:["Recuperação","Esforço","Sono","Progresso do plano","Pronto","Moderado","Ótimo","Semana","semanas","Explorar"],signin:["Acesso de membros","Bem-vindo de volta.","O acesso abre por fases para membros fundadores.","E-mail","Palavra-passe","Ainda não és membro? Entra na lista"]},
  it:{band:["Il bracciale Terrifit","Un bracciale. Ogni versione di te.","Misurazione continua per allenamento, lavoro e tutto ciò che viene dopo.",["Rilevamento continuo","Ora a colpo d’occhio","Batteria a 4 punti","Tessuto per la vita reale"],"Scopri il bracciale"],app:["Un’unica piattaforma","Interfacce scura e chiara","Scarica su","Disponibile su","In lista","membri fondatori finora"],lifestyle:["Allenati.","Lavora.","Vivi.","Un segnale. Ogni versione di te."],shop:["Marketplace dei creator","Nutri il tuo meglio.","Prodotti Terrifit e di partner verificati.","Affiliazione","Potremmo ricevere una commissione.","Vedi il marketplace","Partner verificato","Originale Terrifit"],waitlist:["I pionieri riceveranno un regalo di lancio speciale.","membri fondatori","posti creator disponibili","Posto assicurato.","Fatto"],common:["Recupero","Sforzo","Sonno","Progresso del programma","Pronto","Moderato","Ottimale","Settimana","settimane","Scopri"],signin:["Accesso membri","Bentornato.","L’accesso si apre a fasi per i membri fondatori.","E-mail","Password","Non sei membro? Entra nella lista"]},
  tr:{band:["Terrifit Bileklik","Tek bileklik. Her hâlin.","Antrenman, iş ve sonrasındaki her şey için kesintisiz performans ölçümü.",["Kesintisiz ölçüm","Bir bakışta saat","4 noktalı pil","Gerçek hayat için dokuma"],"Bilekliği keşfet"],app:["Tek platform","Koyu ve açık arayüz","Buradan indir","Şuradan edin","Listede","şu ana kadar kurucu üye"],lifestyle:["Antrenman yap.","Çalış.","Yaşa.","Tek sinyal. Her hâlin."],shop:["Üretici pazarı","En iyini besle.","Terrifit ürünleri ve doğrulanmış ortak ürünleri.","Satış ortaklığı","Komisyon kazanabiliriz.","Pazarı görüntüle","Doğrulanmış ortak","Terrifit orijinali"],waitlist:["Öncüler özel bir lansman hediyesi alacak.","kurucu üye","kalan üretici yeri","Yerin ayrıldı.","Tamam"],common:["Toparlanma","Yük","Uyku","Program ilerlemesi","Hazır","Orta","Optimum","Hafta","hafta","Keşfet"],signin:["Üye girişi","Tekrar hoş geldin.","Erişim kurucu üyelere aşamalı olarak açılıyor.","E-posta","Şifre","Üye değil misin? Bekleme listesine katıl"]},
  ru:{band:["Браслет Terrifit","Один браслет. Все версии тебя.","Непрерывное измерение показателей на тренировке, работе и после.",["Непрерывные измерения","Время одним взглядом","Батарея с 4 точками","Ткань для реальной жизни"],"О браслете"],app:["Одна платформа","Тёмный и светлый интерфейс","Загрузить в","Доступно в","В списке","участников-основателей"],lifestyle:["Тренируйся.","Работай.","Живи.","Один сигнал. Все версии тебя."],shop:["Маркетплейс авторов","Поддержи лучшую форму.","Продукты Terrifit и проверенных партнёров.","Партнёрская программа","Мы можем получить комиссию.","Открыть маркетплейс","Проверенный партнёр","Оригинал Terrifit"],waitlist:["Пионеры получат особый подарок к запуску.","участников-основателей","мест для авторов осталось","Место закреплено.","Готово"],common:["Восстановление","Нагрузка","Сон","Прогресс плана","Готов","Умеренно","Оптимально","Неделя","недель","Открыть"],signin:["Доступ для участников","С возвращением.","Доступ открывается поэтапно для основателей.","Эл. почта","Пароль","Ещё не участник? Встать в очередь"]},
};
