const en = {
  weekLabel: "Week", coach: "Coach", guided: "Guided coaching", next: "Your next session", adjust: "Adjust with Coach", start: "Start session", paused: "Session paused", review: "Review your plan", choose: "Find your Map", empty: "Give your training a direction.", emptyBody: "Choose a programme in Maps. Your next session and coaching options will appear here.",
  title: "Make the plan fit.", intro: "Tell us what today has room for. Review every change before it reaches your workout.", time: "Time available", feeling: "How do you feel?", ready: "Ready", tired: "Low energy", pain: "Pain or unwell", propose: "Review an adjustment", original: "Original", proposed: "Proposed", exercises: "exercises", minutes: "min", apply: "Apply to this session", undo: "Restore original session", applied: "Your adjustment is saved.", savedBody: "Your workout will open with the accepted exercises. You can restore the original before starting.", restBody: "Your programme stays where it is. You can revisit this decision before starting a workout.", explain: "Why this change", keeps: "What changes", working: "Saving…", error: "We couldn’t save that change. Try again.", retry: "Try again", method: "Built from your programme and this check-in. Guided rules, not a medical assessment or an AI chat. Health scores do not change the prescription.", week: "Your last 7 days", progress: "Progress", sessions: "Sessions", activeDays: "Active days", trainingTime: "Logged minutes", weekTitle: "Work you showed up for.", weekBody: "Every completed session counts. Build a rhythm that leaves room for real life.", share: "Share your week", sharePreview: "Your share preview", privacy: "Only this summary is shared. No health readings, weight, name or profile details.", noWork: "Your first session starts the story.", noWorkBody: "Finish and save a workout to see it here. There is no streak to lose.", more: "Explore your trends", body: "Body measurements", stale: "Older readings", staleBody: "These readings are from a previous day. Sync before using them as context for today.", updated: "Reading date", weekLink: "View your week", back: "Back", why: "How this works",
};
const ar: typeof en = {
  weekLabel: "أسبوع", coach: "المدرب", guided: "توجيه التدريب", next: "جلستك التالية", adjust: "عدّل مع المدرب", start: "ابدأ الجلسة", paused: "الجلسة متوقفة", review: "راجع خطتك", choose: "اختر برنامجك", empty: "حدّد اتجاه تدريبك.", emptyBody: "اختر برنامجاً من Maps لتظهر جلستك التالية وخيارات التوجيه هنا.",
  title: "خطة تناسب يومك.", intro: "أخبرنا بما يسمح به يومك. راجع كل تعديل قبل تطبيقه على تدريبك.", time: "الوقت المتاح", feeling: "كيف تشعر؟", ready: "مستعد", tired: "طاقة منخفضة", pain: "ألم أو تعب", propose: "راجع تعديلاً", original: "الأصلية", proposed: "المقترحة", exercises: "تمارين", minutes: "دقيقة", apply: "طبّق على هذه الجلسة", undo: "استعد الجلسة الأصلية", applied: "تم حفظ تعديلك.", savedBody: "ستفتح الجلسة بالتمارين التي وافقت عليها. يمكنك استعادة الأصل قبل البدء.", restBody: "يبقى برنامجك في موضعه. يمكنك مراجعة هذا القرار قبل بدء التدريب.", explain: "سبب التعديل", keeps: "ما الذي يتغير", working: "جارٍ الحفظ…", error: "تعذّر حفظ التعديل. حاول مجدداً.", retry: "حاول مجدداً", method: "يعتمد على برنامجك وإجاباتك. توجيه بقواعد محددة، وليس تقييماً طبياً أو محادثة ذكاء اصطناعي. مؤشرات الصحة لا تغيّر وصفة التدريب.", week: "آخر ٧ أيام", progress: "التقدم", sessions: "جلسات", activeDays: "أيام نشطة", trainingTime: "دقائق مسجلة", weekTitle: "جهدك يستحق أن تراه.", weekBody: "كل جلسة مكتملة تُحسب. ابنِ إيقاعاً يناسب حياتك.", share: "شارك أسبوعك", sharePreview: "معاينة المشاركة", privacy: "تشارك هذا الملخص فقط، دون مؤشرات صحية أو وزن أو اسم أو تفاصيل الملف.", noWork: "جلستك الأولى تبدأ القصة.", noWorkBody: "أكمل تدريباً واحفظه ليظهر هنا. لا توجد سلسلة تخسرها.", more: "استكشف اتجاهاتك", body: "قياسات الجسم", stale: "قراءات سابقة", staleBody: "هذه القراءات من يوم سابق. زامن بياناتك قبل استخدامها كسياق ليومك.", updated: "تاريخ القراءة", weekLink: "شاهد أسبوعك", back: "رجوع", why: "كيف يعمل التوجيه",
};
export function coachingCopy(locale: string) { return locale === "ar" ? ar : en; }
