import type { AppLocale } from "@/preferences";

export type CommerceCopy = {
  shopTitle: string; shopEyebrow: string; offline: string; result: string; results: string; forQuery: string;
  noMatch: string; noMatchBody: string; showAll: string; yourV1: string; yours: string; woven: string;
  bicepTitle: string; bicepBody: string; partner: string; original: string; save: string;
  colourway: string; option: string; required: string; verifiedPartner: string; terrifitOriginal: string;
  fullSpecs: string; specification: string; unavailable: string; unavailableBody: string; back: string; bag: string;
  inBag: string; view: string; chooseOption: string; addToBag: string; outOfStock?: string;
  yourBag: string; clear: string; emptyBag: string; emptyBagBody: string; openShop: string; remove: string;
  boughtTogether: string; pickedTogether: string; pastOrders: (count: number) => string; subtotal: string;
  taxShipping: string; checkout: string; choose: string; add: string; fewer: string; more: string;
};

export const commerceCopy: Record<AppLocale, CommerceCopy> = {
  en: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + verified partners",offline:"Couldn't load the shop. Pull down to try again.",result:"result",results:"results",forQuery:"for",noMatch:"Nothing matches that",noMatchBody:"Try a shorter word, or clear the filter — we carry Terrifuel, recovery, apparel and everything for the V1.",showAll:"Show everything",yourV1:"Your V1",yours:"Yours",woven:"Woven",bicepTitle:"V1 Bicep Strap",bicepBody:"Moves the sensor above the elbow, where the arm is still. The trace stays clean through a heavy set.",partner:"PARTNER",original:"TERRIFIT",save:"SAVE",colourway:"Colourway",option:"Option",required:"required",verifiedPartner:"Verified partner",terrifitOriginal:"Terrifit original",fullSpecs:"The full spec sheet",specification:"Specification",unavailable:"Unavailable",unavailableBody:"We couldn't load this product. Pull back and try again.",back:"Back",bag:"Bag",inBag:"In your bag",view:"View",chooseOption:"Choose an option",addToBag:"Add to bag",outOfStock:"Out of stock",yourBag:"Your bag",clear:"Clear",emptyBag:"Nothing in the bag",emptyBagBody:"Supplements, straps and the V1 all live in Terrifuel.",openShop:"Open Terrifuel",remove:"Remove",boughtTogether:"Usually bought together",pickedTogether:"Picked to go with what is in your bag.",pastOrders:(count)=>`From ${count} past orders that included what is in your bag.`,subtotal:"Subtotal",taxShipping:"Tax and shipping are worked out at checkout.",checkout:"Checkout",choose:"Choose",add:"Add",fewer:"Fewer",more:"More",
  },
  es: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + socios verificados",offline:"No se pudo cargar la tienda. Desliza hacia abajo para reintentar.",result:"resultado",results:"resultados",forQuery:"para",noMatch:"No hay coincidencias",noMatchBody:"Prueba una palabra más corta o borra el filtro: tenemos Terrifuel, recuperación, ropa y todo para V1.",showAll:"Mostrar todo",yourV1:"Tu V1",yours:"Tuya",woven:"Tejida",bicepTitle:"Correa de bíceps V1",bicepBody:"Coloca el sensor sobre el codo, donde el brazo permanece estable. La lectura se mantiene limpia durante las series pesadas.",partner:"SOCIO",original:"TERRIFIT",save:"AHORRA",colourway:"Color",option:"Opción",required:"obligatorio",verifiedPartner:"Socio verificado",terrifitOriginal:"Original Terrifit",fullSpecs:"Ficha técnica completa",specification:"Especificaciones",unavailable:"No disponible",unavailableBody:"No pudimos cargar este producto. Vuelve atrás e inténtalo de nuevo.",back:"Atrás",bag:"Bolsa",inBag:"En tu bolsa",view:"Ver",chooseOption:"Elige una opción",addToBag:"Añadir a la bolsa",yourBag:"Tu bolsa",clear:"Vaciar",emptyBag:"La bolsa está vacía",emptyBagBody:"Los suplementos, correas y V1 están en Terrifuel.",openShop:"Abrir Terrifuel",remove:"Eliminar",boughtTogether:"Suelen comprarse juntos",pickedTogether:"Elegidos para combinar con tu bolsa.",pastOrders:(count)=>`Basado en ${count} pedidos anteriores con productos de tu bolsa.`,subtotal:"Subtotal",taxShipping:"Los impuestos y el envío se calculan al pagar.",checkout:"Pagar",choose:"Elegir",add:"Añadir",fewer:"Menos",more:"Más",
  },
  ar: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + شركاء موثوقون",offline:"تعذر تحميل المتجر. اسحب للأسفل للمحاولة مجدداً.",result:"نتيجة",results:"نتائج",forQuery:"عن",noMatch:"لا توجد نتائج مطابقة",noMatchBody:"جرّب كلمة أقصر أو أزل الفلتر — نوفر Terrifuel ومنتجات الاستشفاء والملابس وكل ما يخص V1.",showAll:"عرض الكل",yourV1:"جهاز V1 الخاص بك",yours:"لك",woven:"منسوج",bicepTitle:"حزام العضد V1",bicepBody:"ينقل المستشعر فوق المرفق حيث يكون الذراع ثابتاً، لتحافظ القراءة على دقتها أثناء التمرين الثقيل.",partner:"شريك",original:"TERRIFIT",save:"وفّر",colourway:"اللون",option:"الخيار",required:"مطلوب",verifiedPartner:"شريك موثوق",terrifitOriginal:"منتج Terrifit أصلي",fullSpecs:"المواصفات الكاملة",specification:"المواصفات",unavailable:"غير متاح",unavailableBody:"تعذر تحميل هذا المنتج. ارجع وحاول مجدداً.",back:"رجوع",bag:"السلة",inBag:"في سلتك",view:"عرض",chooseOption:"اختر خياراً",addToBag:"أضف إلى السلة",yourBag:"سلتك",clear:"إفراغ",emptyBag:"السلة فارغة",emptyBagBody:"المكملات والأحزمة وV1 كلها في Terrifuel.",openShop:"افتح Terrifuel",remove:"إزالة",boughtTogether:"تُشترى معاً عادةً",pickedTogether:"مختارة لتناسب ما في سلتك.",pastOrders:(count)=>`استناداً إلى ${count} طلبات سابقة تضمنت ما في سلتك.`,subtotal:"المجموع الفرعي",taxShipping:"تُحسب الضرائب والشحن عند الدفع.",checkout:"الدفع",choose:"اختر",add:"أضف",fewer:"أقل",more:"أكثر",
  },
  fr: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + partenaires vérifiés",offline:"Impossible de charger la boutique. Tirez vers le bas pour réessayer.",result:"résultat",results:"résultats",forQuery:"pour",noMatch:"Aucun résultat",noMatchBody:"Essayez un mot plus court ou effacez le filtre : Terrifuel, récupération, vêtements et tout pour la V1.",showAll:"Tout afficher",yourV1:"Votre V1",yours:"À vous",woven:"Tissé",bicepTitle:"Bracelet biceps V1",bicepBody:"Place le capteur au-dessus du coude, là où le bras reste stable. Le tracé reste net pendant les séries lourdes.",partner:"PARTENAIRE",original:"TERRIFIT",save:"ÉCONOMISEZ",colourway:"Coloris",option:"Option",required:"obligatoire",verifiedPartner:"Partenaire vérifié",terrifitOriginal:"Original Terrifit",fullSpecs:"Fiche technique complète",specification:"Caractéristiques",unavailable:"Indisponible",unavailableBody:"Impossible de charger ce produit. Revenez en arrière et réessayez.",back:"Retour",bag:"Panier",inBag:"Dans votre panier",view:"Voir",chooseOption:"Choisissez une option",addToBag:"Ajouter au panier",yourBag:"Votre panier",clear:"Vider",emptyBag:"Votre panier est vide",emptyBagBody:"Compléments, bracelets et V1 sont dans Terrifuel.",openShop:"Ouvrir Terrifuel",remove:"Retirer",boughtTogether:"Souvent achetés ensemble",pickedTogether:"Choisis pour accompagner votre panier.",pastOrders:(count)=>`D'après ${count} commandes précédentes contenant les articles de votre panier.`,subtotal:"Sous-total",taxShipping:"Taxes et livraison sont calculées au paiement.",checkout:"Commander",choose:"Choisir",add:"Ajouter",fewer:"Moins",more:"Plus",
  },
  de: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + geprüfte Partner",offline:"Shop konnte nicht geladen werden. Zum Wiederholen nach unten ziehen.",result:"Ergebnis",results:"Ergebnisse",forQuery:"für",noMatch:"Keine Treffer",noMatchBody:"Versuche ein kürzeres Wort oder lösche den Filter – Terrifuel, Regeneration, Kleidung und alles für V1.",showAll:"Alles anzeigen",yourV1:"Deine V1",yours:"Deins",woven:"Gewebt",bicepTitle:"V1-Bizepsband",bicepBody:"Setzt den Sensor über den Ellenbogen, wo der Arm ruhig bleibt. Die Kurve bleibt auch bei schweren Sätzen sauber.",partner:"PARTNER",original:"TERRIFIT",save:"SPAREN",colourway:"Farbe",option:"Option",required:"erforderlich",verifiedPartner:"Geprüfter Partner",terrifitOriginal:"Terrifit Original",fullSpecs:"Vollständiges Datenblatt",specification:"Spezifikation",unavailable:"Nicht verfügbar",unavailableBody:"Dieses Produkt konnte nicht geladen werden. Geh zurück und versuche es erneut.",back:"Zurück",bag:"Warenkorb",inBag:"Im Warenkorb",view:"Ansehen",chooseOption:"Option wählen",addToBag:"In den Warenkorb",yourBag:"Dein Warenkorb",clear:"Leeren",emptyBag:"Warenkorb ist leer",emptyBagBody:"Supplements, Bänder und V1 findest du bei Terrifuel.",openShop:"Terrifuel öffnen",remove:"Entfernen",boughtTogether:"Oft zusammen gekauft",pickedTogether:"Passend zu deinem Warenkorb ausgewählt.",pastOrders:(count)=>`Aus ${count} früheren Bestellungen mit Artikeln aus deinem Warenkorb.`,subtotal:"Zwischensumme",taxShipping:"Steuern und Versand werden beim Bezahlen berechnet.",checkout:"Zur Kasse",choose:"Wählen",add:"Hinzufügen",fewer:"Weniger",more:"Mehr",
  },
  nl: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + geverifieerde partners",offline:"De winkel kon niet worden geladen. Trek omlaag om opnieuw te proberen.",result:"resultaat",results:"resultaten",forQuery:"voor",noMatch:"Geen resultaten",noMatchBody:"Probeer een korter woord of wis het filter — Terrifuel, herstel, kleding en alles voor V1.",showAll:"Alles tonen",yourV1:"Jouw V1",yours:"Van jou",woven:"Geweven",bicepTitle:"V1-bicepsband",bicepBody:"Plaatst de sensor boven de elleboog, waar de arm stil blijft. De meting blijft schoon tijdens een zware set.",partner:"PARTNER",original:"TERRIFIT",save:"BESPAAR",colourway:"Kleur",option:"Optie",required:"verplicht",verifiedPartner:"Geverifieerde partner",terrifitOriginal:"Terrifit origineel",fullSpecs:"Volledig specificatieblad",specification:"Specificaties",unavailable:"Niet beschikbaar",unavailableBody:"Dit product kon niet worden geladen. Ga terug en probeer opnieuw.",back:"Terug",bag:"Mandje",inBag:"In je mandje",view:"Bekijken",chooseOption:"Kies een optie",addToBag:"In mandje",yourBag:"Jouw mandje",clear:"Wissen",emptyBag:"Je mandje is leeg",emptyBagBody:"Supplementen, bandjes en V1 vind je bij Terrifuel.",openShop:"Terrifuel openen",remove:"Verwijderen",boughtTogether:"Vaak samen gekocht",pickedTogether:"Gekozen bij wat er in je mandje zit.",pastOrders:(count)=>`Gebaseerd op ${count} eerdere bestellingen met artikelen uit je mandje.`,subtotal:"Subtotaal",taxShipping:"Belasting en verzending worden bij het afrekenen berekend.",checkout:"Afrekenen",choose:"Kiezen",add:"Toevoegen",fewer:"Minder",more:"Meer",
  },
  pt: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + parceiros verificados",offline:"Não foi possível carregar a loja. Puxa para baixo para tentar novamente.",result:"resultado",results:"resultados",forQuery:"para",noMatch:"Sem resultados",noMatchBody:"Experimenta uma palavra mais curta ou limpa o filtro — Terrifuel, recuperação, roupa e tudo para a V1.",showAll:"Mostrar tudo",yourV1:"A tua V1",yours:"Tua",woven:"Tecido",bicepTitle:"Pulseira de bíceps V1",bicepBody:"Coloca o sensor acima do cotovelo, onde o braço fica estável. A leitura mantém-se limpa em séries pesadas.",partner:"PARCEIRO",original:"TERRIFIT",save:"POUPA",colourway:"Cor",option:"Opção",required:"obrigatório",verifiedPartner:"Parceiro verificado",terrifitOriginal:"Original Terrifit",fullSpecs:"Ficha técnica completa",specification:"Especificações",unavailable:"Indisponível",unavailableBody:"Não foi possível carregar este produto. Volta atrás e tenta novamente.",back:"Voltar",bag:"Saco",inBag:"No teu saco",view:"Ver",chooseOption:"Escolhe uma opção",addToBag:"Adicionar ao saco",yourBag:"O teu saco",clear:"Limpar",emptyBag:"O saco está vazio",emptyBagBody:"Suplementos, pulseiras e a V1 estão na Terrifuel.",openShop:"Abrir Terrifuel",remove:"Remover",boughtTogether:"Comprados juntos com frequência",pickedTogether:"Escolhidos para acompanhar o que está no teu saco.",pastOrders:(count)=>`Com base em ${count} encomendas anteriores com artigos do teu saco.`,subtotal:"Subtotal",taxShipping:"Impostos e envio são calculados no pagamento.",checkout:"Finalizar compra",choose:"Escolher",add:"Adicionar",fewer:"Menos",more:"Mais",
  },
  it: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + partner verificati",offline:"Impossibile caricare il negozio. Trascina in basso per riprovare.",result:"risultato",results:"risultati",forQuery:"per",noMatch:"Nessun risultato",noMatchBody:"Prova una parola più breve o cancella il filtro — Terrifuel, recupero, abbigliamento e tutto per V1.",showAll:"Mostra tutto",yourV1:"La tua V1",yours:"Tuo",woven:"Intrecciato",bicepTitle:"Fascia bicipite V1",bicepBody:"Sposta il sensore sopra il gomito, dove il braccio resta fermo. La lettura rimane pulita durante le serie pesanti.",partner:"PARTNER",original:"TERRIFIT",save:"RISPARMIA",colourway:"Colore",option:"Opzione",required:"obbligatorio",verifiedPartner:"Partner verificato",terrifitOriginal:"Originale Terrifit",fullSpecs:"Scheda tecnica completa",specification:"Specifiche",unavailable:"Non disponibile",unavailableBody:"Impossibile caricare questo prodotto. Torna indietro e riprova.",back:"Indietro",bag:"Carrello",inBag:"Nel carrello",view:"Vedi",chooseOption:"Scegli un'opzione",addToBag:"Aggiungi al carrello",yourBag:"Il tuo carrello",clear:"Svuota",emptyBag:"Il carrello è vuoto",emptyBagBody:"Integratori, cinturini e V1 sono in Terrifuel.",openShop:"Apri Terrifuel",remove:"Rimuovi",boughtTogether:"Spesso acquistati insieme",pickedTogether:"Scelti per accompagnare il tuo carrello.",pastOrders:(count)=>`Da ${count} ordini precedenti che includevano articoli nel tuo carrello.`,subtotal:"Subtotale",taxShipping:"Imposte e spedizione vengono calcolate al pagamento.",checkout:"Vai al pagamento",choose:"Scegli",add:"Aggiungi",fewer:"Meno",more:"Più",
  },
  tr: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + doğrulanmış ortaklar",offline:"Mağaza yüklenemedi. Tekrar denemek için aşağı çek.",result:"sonuç",results:"sonuç",forQuery:"için",noMatch:"Eşleşme yok",noMatchBody:"Daha kısa bir kelime dene veya filtreyi temizle — Terrifuel, toparlanma, giyim ve V1 için her şey burada.",showAll:"Tümünü göster",yourV1:"V1'in",yours:"Senin",woven:"Dokuma",bicepTitle:"V1 pazu kayışı",bicepBody:"Sensörü dirseğin üstüne, kolun sabit kaldığı yere taşır. Ağır setlerde ölçüm temiz kalır.",partner:"ORTAK",original:"TERRIFIT",save:"KAZAN",colourway:"Renk",option:"Seçenek",required:"gerekli",verifiedPartner:"Doğrulanmış ortak",terrifitOriginal:"Terrifit orijinal",fullSpecs:"Tam teknik bilgiler",specification:"Teknik özellikler",unavailable:"Kullanılamıyor",unavailableBody:"Bu ürün yüklenemedi. Geri dönüp tekrar dene.",back:"Geri",bag:"Sepet",inBag:"Sepetinde",view:"Görüntüle",chooseOption:"Bir seçenek seç",addToBag:"Sepete ekle",yourBag:"Sepetin",clear:"Temizle",emptyBag:"Sepet boş",emptyBagBody:"Takviyeler, kayışlar ve V1 Terrifuel'de.",openShop:"Terrifuel'i aç",remove:"Kaldır",boughtTogether:"Genellikle birlikte alınır",pickedTogether:"Sepetindekilerle uyumlu olarak seçildi.",pastOrders:(count)=>`Sepetindekileri içeren ${count} geçmiş siparişe göre.`,subtotal:"Ara toplam",taxShipping:"Vergi ve kargo ödeme sırasında hesaplanır.",checkout:"Ödemeye geç",choose:"Seç",add:"Ekle",fewer:"Daha az",more:"Daha fazla",
  },
  ru: {
    shopTitle:"Terrifuel",shopEyebrow:"Terrifit + проверенные партнёры",offline:"Не удалось загрузить магазин. Потяните вниз, чтобы повторить.",result:"результат",results:"результатов",forQuery:"по запросу",noMatch:"Ничего не найдено",noMatchBody:"Попробуйте более короткое слово или сбросьте фильтр — Terrifuel, восстановление, одежда и всё для V1.",showAll:"Показать всё",yourV1:"Ваш V1",yours:"Ваш",woven:"Тканый",bicepTitle:"Ремешок V1 на бицепс",bicepBody:"Перемещает датчик выше локтя, где рука неподвижна. Измерения остаются точными во время тяжёлых подходов.",partner:"ПАРТНЁР",original:"TERRIFIT",save:"СКИДКА",colourway:"Цвет",option:"Вариант",required:"обязательно",verifiedPartner:"Проверенный партнёр",terrifitOriginal:"Оригинал Terrifit",fullSpecs:"Полные характеристики",specification:"Характеристики",unavailable:"Недоступно",unavailableBody:"Не удалось загрузить товар. Вернитесь назад и попробуйте снова.",back:"Назад",bag:"Корзина",inBag:"В корзине",view:"Открыть",chooseOption:"Выберите вариант",addToBag:"В корзину",yourBag:"Ваша корзина",clear:"Очистить",emptyBag:"Корзина пуста",emptyBagBody:"Добавки, ремешки и V1 находятся в Terrifuel.",openShop:"Открыть Terrifuel",remove:"Удалить",boughtTogether:"Обычно покупают вместе",pickedTogether:"Подобрано к товарам в вашей корзине.",pastOrders:(count)=>`По данным ${count} прошлых заказов с товарами из вашей корзины.`,subtotal:"Промежуточный итог",taxShipping:"Налоги и доставка рассчитываются при оплате.",checkout:"Оформить",choose:"Выбрать",add:"Добавить",fewer:"Меньше",more:"Больше",
  },
};

export const commerceCategories: Record<AppLocale, Record<string, string>> = {
  en: { all:"All", band:"Band", accessories:"Accessories", apparel:"Apparel", fuel:"Supplements", recovery:"Recovery" },
  es: { all:"Todo", band:"Pulsera", accessories:"Accesorios", apparel:"Ropa", fuel:"Suplementos", recovery:"Recuperación" },
  ar: { all:"الكل", band:"السوار", accessories:"الإكسسوارات", apparel:"الملابس", fuel:"المكملات", recovery:"الاستشفاء" },
  fr: { all:"Tout", band:"Bracelet", accessories:"Accessoires", apparel:"Vêtements", fuel:"Compléments", recovery:"Récupération" },
  de: { all:"Alle", band:"Band", accessories:"Zubehör", apparel:"Bekleidung", fuel:"Supplements", recovery:"Regeneration" },
  nl: { all:"Alles", band:"Band", accessories:"Accessoires", apparel:"Kleding", fuel:"Supplementen", recovery:"Herstel" },
  pt: { all:"Tudo", band:"Pulseira", accessories:"Acessórios", apparel:"Roupa", fuel:"Suplementos", recovery:"Recuperação" },
  it: { all:"Tutto", band:"Fascia", accessories:"Accessori", apparel:"Abbigliamento", fuel:"Integratori", recovery:"Recupero" },
  tr: { all:"Tümü", band:"Bant", accessories:"Aksesuar", apparel:"Giyim", fuel:"Takviyeler", recovery:"Toparlanma" },
  ru: { all:"Все", band:"Браслет", accessories:"Аксессуары", apparel:"Одежда", fuel:"Добавки", recovery:"Восстановление" },
};
