import type { AppLocale } from "@/preferences";

type SettingsCopy = {
  systemHint: string; languageHint: string; shareTitle: string; shareDetail: string;
  signedInAs: string; member: string; profileDetails: string; profileDetail: string;
  measurement: string; measurementHint: string;
};

export const settingsCopy: Record<AppLocale, SettingsCopy> = {
  en:{systemHint:"System follows your device. Changes move through a short in-app transition.",languageHint:"Translated areas update instantly. Arabic changes direction the next time the app opens.",shareTitle:"Share trends with my coach",shareDetail:"Your private check-ins stay private. This shares high-level progress trends only.",signedInAs:"Signed in as",member:"Terrifit member",profileDetails:"Profile details",profileDetail:"Name, handle, bio and training goal",measurement:"Measurement system",measurementHint:"Used for weight, height, distance and report values."},
  es:{systemHint:"Sistema sigue los ajustes del dispositivo. Los cambios usan una breve transición dentro de la app.",languageHint:"Las áreas traducidas se actualizan al instante. El árabe cambia la dirección al volver a abrir la app.",shareTitle:"Compartir tendencias con mi entrenador",shareDetail:"Tus registros privados siguen siendo privados. Solo se comparten tendencias generales de progreso.",signedInAs:"Sesión iniciada como",member:"Miembro de Terrifit",profileDetails:"Datos del perfil",profileDetail:"Nombre, usuario, biografía y objetivo de entrenamiento",measurement:"Sistema de medidas",measurementHint:"Se usa para peso, altura, distancia e informes."},
  ar:{systemHint:"يتبع خيار النظام إعداد جهازك، وتظهر التغييرات عبر انتقال قصير داخل التطبيق.",languageHint:"تتحدث الأقسام المترجمة فوراً. يُطبّق اتجاه العربية عند فتح التطبيق في المرة التالية.",shareTitle:"مشاركة الاتجاهات مع مدربي",shareDetail:"تبقى تسجيلاتك الخاصة سرية، ولا تتم مشاركة سوى اتجاهات التقدم العامة.",signedInAs:"تم تسجيل الدخول باسم",member:"عضو Terrifit",profileDetails:"تفاصيل الملف",profileDetail:"الاسم واسم المستخدم والنبذة وهدف التدريب",measurement:"نظام القياس",measurementHint:"يُستخدم للوزن والطول والمسافة وقيم التقارير."},
  fr:{systemHint:"Le mode système suit votre appareil. Les changements passent par une courte transition dans l’app.",languageHint:"Les zones traduites se mettent à jour immédiatement. Le sens de l’arabe s’applique à la prochaine ouverture.",shareTitle:"Partager mes tendances avec mon coach",shareDetail:"Vos suivis privés le restent. Seules les tendances générales de progression sont partagées.",signedInAs:"Connecté en tant que",member:"Membre Terrifit",profileDetails:"Détails du profil",profileDetail:"Nom, identifiant, bio et objectif d’entraînement",measurement:"Système de mesure",measurementHint:"Utilisé pour le poids, la taille, la distance et les rapports."},
  de:{systemHint:"System folgt deinem Gerät. Änderungen laufen über einen kurzen Übergang in der App.",languageHint:"Übersetzte Bereiche werden sofort aktualisiert. Arabisch wechselt die Richtung beim nächsten Öffnen.",shareTitle:"Trends mit meinem Coach teilen",shareDetail:"Deine privaten Check-ins bleiben privat. Nur übergeordnete Fortschrittstrends werden geteilt.",signedInAs:"Angemeldet als",member:"Terrifit-Mitglied",profileDetails:"Profildetails",profileDetail:"Name, Benutzername, Bio und Trainingsziel",measurement:"Maßsystem",measurementHint:"Wird für Gewicht, Größe, Distanz und Berichtswerte verwendet."},
  nl:{systemHint:"Systeem volgt je apparaat. Wijzigingen verschijnen via een korte overgang in de app.",languageHint:"Vertaalde onderdelen wijzigen direct. Arabisch past de richting toe wanneer je de app opnieuw opent.",shareTitle:"Trends delen met mijn coach",shareDetail:"Je privé-check-ins blijven privé. Alleen algemene voortgangstrends worden gedeeld.",signedInAs:"Ingelogd als",member:"Terrifit-lid",profileDetails:"Profielgegevens",profileDetail:"Naam, gebruikersnaam, bio en trainingsdoel",measurement:"Meetsysteem",measurementHint:"Gebruikt voor gewicht, lengte, afstand en rapportwaarden."},
  pt:{systemHint:"O sistema segue o dispositivo. As alterações usam uma breve transição na app.",languageHint:"As áreas traduzidas atualizam de imediato. O árabe muda a direção na próxima abertura.",shareTitle:"Partilhar tendências com o meu treinador",shareDetail:"Os teus registos privados continuam privados. Só são partilhadas tendências gerais de progresso.",signedInAs:"Sessão iniciada como",member:"Membro Terrifit",profileDetails:"Detalhes do perfil",profileDetail:"Nome, utilizador, biografia e objetivo de treino",measurement:"Sistema de medidas",measurementHint:"Usado para peso, altura, distância e valores dos relatórios."},
  it:{systemHint:"Il sistema segue il dispositivo. Le modifiche usano una breve transizione nell’app.",languageHint:"Le aree tradotte si aggiornano subito. L’arabo cambia direzione alla prossima apertura.",shareTitle:"Condividi l’andamento con il mio coach",shareDetail:"I tuoi check-in privati restano privati. Vengono condivise solo tendenze generali dei progressi.",signedInAs:"Accesso effettuato come",member:"Membro Terrifit",profileDetails:"Dettagli del profilo",profileDetail:"Nome, username, bio e obiettivo di allenamento",measurement:"Sistema di misura",measurementHint:"Usato per peso, altezza, distanza e valori nei report."},
  tr:{systemHint:"Sistem cihazını takip eder. Değişiklikler uygulama içi kısa bir geçişle uygulanır.",languageHint:"Çevrilen alanlar anında güncellenir. Arapça yönü uygulama bir sonraki açıldığında uygulanır.",shareTitle:"Eğilimleri koçumla paylaş",shareDetail:"Özel check-in'lerin gizli kalır. Yalnızca üst düzey ilerleme eğilimleri paylaşılır.",signedInAs:"Oturum açılan hesap",member:"Terrifit üyesi",profileDetails:"Profil ayrıntıları",profileDetail:"Ad, kullanıcı adı, bio ve antrenman hedefi",measurement:"Ölçüm sistemi",measurementHint:"Ağırlık, boy, mesafe ve rapor değerlerinde kullanılır."},
  ru:{systemHint:"Системная тема следует настройкам устройства. Изменения применяются с короткой анимацией внутри приложения.",languageHint:"Переведённые разделы обновляются сразу. Направление арабского применяется при следующем запуске.",shareTitle:"Делиться трендами с тренером",shareDetail:"Личные отметки останутся закрытыми. Передаются только общие тенденции прогресса.",signedInAs:"Вход выполнен как",member:"Участник Terrifit",profileDetails:"Данные профиля",profileDetail:"Имя, ник, описание и цель тренировок",measurement:"Система мер",measurementHint:"Используется для веса, роста, расстояния и значений в отчётах."},
};
