import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { AppHeader } from "@/components/AppHeader";
import { Screen } from "@/components/Screen";
import { useMaps, useNotifications } from "@/data";
import { display, theme } from "@/theme";


export default function MapsScreen(){const router=useRouter();const maps=useMaps();const notices=useNotifications();const list=maps.data?.maps??[];return <Screen eyebrow="Plans that adapt" title="Maps" refreshing={maps.refreshing} onRefresh={maps.reload} header={<AppHeader unread={notices.data?.unread??0}/>}>
  <Text style={s.lede}>A programme is only useful if it changes when your body does. Every Map responds to your recovery, schedule and progress.</Text>
  {maps.data?.active.length?<View style={s.active}><Text style={s.kicker}>In progress</Text>{maps.data.active.map(item=><Pressable key={item.mapId} onPress={()=>router.push(`/map/${item.mapId}` as never)} style={s.activeCard}><View style={s.activeTop}><View><Text style={s.activeName}>{item.name}</Text><Text style={s.meta}>Week {item.week} of {item.weeks} · {item.blockLabel}</Text></View><Text style={s.percent}>{item.percent}%</Text></View><View style={s.track}><View style={[s.fill,{width:`${item.percent}%`,backgroundColor:item.accent}]}/></View><Text style={s.meta}>{item.done} of {item.sessionsPerWeek} sessions this week</Text></Pressable>)}</View>:null}
  <View style={s.head}><Text style={s.kicker}>Recommended for you</Text><Text style={s.count}>{maps.data?.total??list.length} Maps</Text></View>
  {maps.loading&&!maps.data?<ActivityIndicator color={theme.accent} style={{marginVertical:30}}/>:null}{maps.error?<Text style={s.offline}>Previewing the Map library while Terrifit reconnects.</Text>:null}
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{["All","Strength","Build","Endurance","Health"].map((x,i)=><View key={x} style={[s.filter,i===0&&s.filterOn]}><Text style={[s.filterText,i===0&&s.filterTextOn]}>{x}</Text></View>)}</ScrollView>
  <View style={s.list}>{list.map(item=><Pressable key={item.id} onPress={()=>router.push(`/map/${item.id}` as never)} style={s.card}><View style={[s.art,{backgroundColor:`${item.accent}20`}]}><View style={[s.artLine,{backgroundColor:item.accent}]}/><Text style={[s.artGoal,{color:item.accent}]}>{item.goal}</Text><Text style={s.artWeeks}>{item.weeks}</Text><Text style={s.artUnit}>WEEKS</Text></View><View style={s.copy}><Text style={s.name}>{item.name}</Text><Text style={s.tagline}>{item.tagline}</Text><Text style={s.coach}>{item.coach.name} · {item.coach.credential}</Text><View style={s.pills}><Text style={s.pill}>{item.level}</Text><Text style={s.pill}>{item.sessionsPerWeek}× week</Text></View></View><Text style={s.arrow}>›</Text></Pressable>)}</View>
  </Screen>}
const s=StyleSheet.create({lede:{color:theme.ink2,fontSize:14,lineHeight:21,marginTop:-10,marginBottom:24},kicker:{color:theme.accent,fontSize:10,fontWeight:"900",letterSpacing:1.6,textTransform:"uppercase"},active:{marginBottom:28},activeCard:{marginTop:12,padding:18,borderRadius:22,borderWidth:1,borderColor:theme.lineStrong,backgroundColor:theme.surface},activeTop:{flexDirection:"row",justifyContent:"space-between"},activeName:{color:theme.ink,fontSize:18,fontWeight:"800"},percent:{color:theme.ink,fontFamily:display,fontSize:28},meta:{color:theme.muted,fontSize:10,marginTop:5},track:{height:5,borderRadius:3,backgroundColor:theme.line,overflow:"hidden",marginTop:16},fill:{height:5,borderRadius:3},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},count:{color:theme.muted,fontSize:10},filters:{gap:8,paddingVertical:14},filter:{paddingHorizontal:14,height:34,borderRadius:17,borderWidth:1,borderColor:theme.line,justifyContent:"center"},filterOn:{backgroundColor:theme.ink,borderColor:theme.ink},filterText:{color:theme.ink2,fontSize:10,fontWeight:"800"},filterTextOn:{color:theme.bg},offline:{color:theme.fair,fontSize:11,marginBottom:8},list:{gap:12},card:{minHeight:150,borderRadius:22,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface,overflow:"hidden",flexDirection:"row",alignItems:"center"},art:{width:112,alignSelf:"stretch",padding:14,justifyContent:"flex-end"},artLine:{position:"absolute",left:0,top:0,bottom:0,width:3},artGoal:{position:"absolute",top:14,left:14,fontSize:10,fontWeight:"900",letterSpacing:1.1,textTransform:"uppercase"},artWeeks:{color:theme.ink,fontFamily:display,fontSize:42},artUnit:{color:theme.ink2,fontSize:10,fontWeight:"900",letterSpacing:1.3},copy:{flex:1,padding:15},name:{color:theme.ink,fontFamily:display,fontSize:23,textTransform:"uppercase"},tagline:{color:theme.ink2,fontSize:12,lineHeight:17,marginTop:4},coach:{color:theme.muted,fontSize:10,marginTop:8},pills:{flexDirection:"row",gap:6,marginTop:10},pill:{color:theme.ink2,fontSize:10,fontWeight:"800",paddingHorizontal:8,paddingVertical:4,borderRadius:9,backgroundColor:theme.bg,overflow:"hidden"},arrow:{color:theme.muted,fontSize:28,marginRight:12}});
