import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { AppHeader } from "@/components/AppHeader";
import { Screen } from "@/components/Screen";
import { useAppState } from "@/app-state";
import { HealthSync } from "@/components/HealthSync";
import { ProBadge } from "@/components/ProBadge";
import { useNotifications } from "@/data";
import { useSession } from "@/session";
import { appearanceMode, display, theme } from "@/theme";
import { localeMeta, usePreferences } from "@/preferences";

export default function ProfileScreen(){const router=useRouter();const {profile,band,refresh}=useAppState();const {name,signOut}=useSession();const preferences=usePreferences();const notices=useNotifications();const user=profile?.user;const details=profile?.profile;const isPro=user?.plan==="pro"||user?.plan==="trial";return <Screen title="" refreshing={false} onRefresh={refresh} header={<AppHeader unread={notices.data?.unread??0}/>}> 
  <View style={s.identity}><View style={s.avatar}><Text style={s.avatarText}>{(user?.name??name??"T").slice(0,1)}</Text></View><View style={s.handleRow}><Text style={s.handle}>{user?.handle?`@${user.handle}`:"Choose your @handle"}</Text>{isPro?<ProBadge/>:null}</View><Text style={s.bio}>{details?.bio??"Your training, recovery and progress in one place."}</Text><View style={s.stats}><Stat value={profile?.stats.posts??0} label="Posts"/><Stat value={profile?.stats.followers??0} label="Followers"/><Stat value={profile?.stats.following??0} label="Following"/></View><Pressable onPress={()=>router.push("/edit-profile" as never)} style={s.edit}><Text style={s.editText}>Edit profile</Text></Pressable></View>
  {isPro?null:<Pressable onPress={()=>router.push("/pro" as never)} style={s.proCta}><View style={{flex:1}}><Text style={s.proCtaTitle}>Become a Pro</Text><Text style={s.proCtaBody}>Sleep quality, load, body battery and insights across your whole history. 14 days free.</Text></View><Text style={s.proCtaArrow}>›</Text></Pressable>}
    {isPro?<Pressable onPress={()=>router.push("/pro" as never)} style={s.proActive}><ProBadge/><View style={{flex:1}}><Text style={s.proActiveTitle}>{user?.plan==="trial"?"Pro trial running":"Terrifit Pro"}</Text><Text style={s.proActiveBody}>Manage your plan</Text></View><Text style={s.proCtaArrow}>›</Text></Pressable>:null}
    {profile?.user.isAdmin?<Pressable onPress={()=>router.push("/admin" as never)} style={s.adminRow}><View style={{flex:1}}><Text style={s.adminTitle}>Console</Text><Text style={s.adminBody}>Members, orders and moderation</Text></View><Text style={s.adminArrow}>›</Text></Pressable>:null}
    <Text style={s.section}>Your data</Text><HealthSync onDone={refresh}/>
    <Text style={s.section}>Your performance</Text><View style={s.menu}><Row title="Trends" detail="Recovery, sleep and movement" onPress={()=>router.push("/(tabs)/trends" as never)}/><Row title="Body" detail="Weight and composition history" onPress={()=>router.push("/(tabs)/body" as never)}/><Row title={band?.band?"Terrifit V1":"Connect a V1"} detail={band?.band?.serial??"Pair your performance band"} onPress={()=>router.push(band?.band?"/(tabs)/band" as never:"/pair-band" as never)}/><Row title="Health connections" detail="Apple Health, Health Connect, InBody"/></View>
  <Text style={s.section}>Profile details</Text><View style={s.details}><Detail label="Goal" value={details?.goal??"Not set"}/><Detail label="Activity" value={details?.activityLevel??"Not set"}/><Detail label="Training" value={details?.trainingDays==null?"Not set":`${details.trainingDays} days / week`}/><Detail label="Units" value={details?.units??"metric"}/></View>
  <Text style={s.section}>{preferences.t("settings")}</Text><View style={s.menu}><Row title={`${preferences.t("appearance")} & ${preferences.t("language")}`} detail={`${preferences.t(appearanceMode)} · ${localeMeta[preferences.locale].label}`} onPress={()=>router.push("/settings" as never)}/><Row title="Notifications" detail="Training, social and V1 alerts" onPress={()=>router.push("/notifications" as never)}/><Row title="Privacy & sharing" detail={details?.shareWithCreators?"Creator trend sharing on":"Private by default"} onPress={()=>router.push("/settings" as never)}/><Row title="Account & security" detail={user?.email??"Manage your sign-in"} onPress={()=>router.push("/settings" as never)}/></View>
  <Pressable onPress={()=>void signOut()} style={s.signout}><Text style={s.signoutText}>Sign out</Text></Pressable>
  </Screen>}
function Stat({value,label}:{value:number;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value.toLocaleString()}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Row({title,detail,onPress}:{title:string;detail:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View><Text style={s.arrow}>›</Text></Pressable>}
function Detail({label,value}:{label:string;value:string}){return <View style={s.detail}><Text style={s.detailLabel}>{label}</Text><Text style={s.detailValue}>{value}</Text></View>}
const s=StyleSheet.create({
  proCta:{flexDirection:"row",alignItems:"center",gap:12,marginTop:20,padding:16,borderRadius:20,borderWidth:1,borderColor:theme.accent,backgroundColor:theme.accentSoft},
  proCtaTitle:{color:theme.accent,fontSize:16,fontWeight:"900"},
  proCtaBody:{color:theme.ink2,fontSize:12,lineHeight:17,marginTop:5},
  proCtaArrow:{color:theme.accent,fontSize:24},
  proActive:{flexDirection:"row",alignItems:"center",gap:12,marginTop:20,padding:16,borderRadius:20,borderWidth:1,borderColor:theme.lineStrong,backgroundColor:theme.surface},
  proActiveTitle:{color:theme.ink,fontSize:15,fontWeight:"900"},
  proActiveBody:{color:theme.muted,fontSize:11,marginTop:4},
  adminRow:{flexDirection:"row",alignItems:"center",gap:12,marginTop:20,padding:15,borderRadius:18,borderWidth:1,borderColor:theme.accent,backgroundColor:theme.accentSoft},adminTitle:{color:theme.accent,fontSize:14,fontWeight:"900"},adminBody:{color:theme.ink2,fontSize:11,marginTop:4},adminArrow:{color:theme.accent,fontSize:24},identity:{alignItems:"center",padding:22,borderRadius:26,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface},avatar:{width:84,height:84,borderRadius:42,backgroundColor:theme.accentSoft,borderWidth:2,borderColor:theme.accent,alignItems:"center",justifyContent:"center"},avatarText:{color:theme.accent,fontFamily:display,fontSize:39},handleRow:{flexDirection:"row",alignItems:"center",gap:8,marginTop:13},handle:{color:theme.ink,fontSize:13,fontWeight:"800"},bio:{color:theme.ink2,fontSize:12,lineHeight:18,textAlign:"center",maxWidth:300,marginTop:7},stats:{flexDirection:"row",alignSelf:"stretch",marginTop:20},stat:{flex:1,alignItems:"center",borderRightWidth:1,borderRightColor:theme.line},statValue:{color:theme.ink,fontSize:18,fontWeight:"900"},statLabel:{color:theme.muted,fontSize:10,fontWeight:"800",textTransform:"uppercase",marginTop:3},edit:{height:42,borderRadius:21,borderWidth:1,borderColor:theme.lineStrong,alignSelf:"stretch",alignItems:"center",justifyContent:"center",marginTop:18},editText:{color:theme.ink,fontSize:10,fontWeight:"900",textTransform:"uppercase",letterSpacing:1},section:{color:theme.accent,fontSize:10,fontWeight:"900",letterSpacing:1.5,textTransform:"uppercase",marginTop:26,marginBottom:10},menu:{borderRadius:20,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface,overflow:"hidden"},row:{minHeight:64,flexDirection:"row",alignItems:"center",paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:theme.line},rowTitle:{color:theme.ink,fontSize:13,fontWeight:"800"},rowDetail:{color:theme.muted,fontSize:10,marginTop:4},arrow:{color:theme.muted,fontSize:24},details:{flexDirection:"row",flexWrap:"wrap",borderRadius:20,borderWidth:1,borderColor:theme.line,backgroundColor:theme.surface,overflow:"hidden"},detail:{width:"50%",padding:16,borderBottomWidth:1,borderRightWidth:1,borderColor:theme.line},detailLabel:{color:theme.muted,fontSize:10,fontWeight:"900",textTransform:"uppercase",letterSpacing:1},detailValue:{color:theme.ink,fontSize:13,fontWeight:"800",marginTop:6,textTransform:"capitalize"},signout:{height:50,borderRadius:25,borderWidth:1,borderColor:theme.lineStrong,alignItems:"center",justifyContent:"center",marginTop:26},signoutText:{color:theme.poor,fontSize:11,fontWeight:"900",textTransform:"uppercase",letterSpacing:1}});
