import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app/AppShell";
import { isLocale } from "@/i18n/config";
import { getPagesCopy } from "@/i18n/pages";
import { getCurrentUser } from "@/lib/auth";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Terrifit",
  // Somebody's own readings. Never an index.
  robots: { index: false, follow: false },
};

// `LayoutProps` is generated by `next typegen` and globally available; it gives
// this layout the params its own route segment actually declares.
export default async function AppLayout({ children, params }: LayoutProps<"/[locale]/app">) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  const user = await getCurrentUser();
  if (!user) redirect(`/${locale}/signin`);

  const copy = getPagesCopy(locale).app;
  return (
    <AppShell locale={locale} copy={copy} name={user.name.split(" ")[0] || user.email}>
      {children}
    </AppShell>
  );
}
